waypoints:
  로비:
    x: 0.017
    y: 0.0
    yaw: -0.264
    aliases:
    - 입구
    - 현관
    - 로비앞
  회의실:
    x: 2.926
    y: 0.218
    yaw: -2.992
    aliases:
    - 미팅룸
    - 회의하는 곳
    - 미팅
  화장실:
    x: 1.309
    y: 0.46
    yaw: -1.758
    aliases:
    - 화장실
    - toilet
    - 세면장
  정수기:
    x: 1.818
    y: -0.478
    yaw: 2.662
    aliases:
    - 물
    - 정수기
    - 식수대
